# This is a basic workflow to help you get started with Actions

name: CXSAST-CLI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "security-scan"
  security-scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Scan code with Checkmarx
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-github-action@v1.0.3
      with:
        cxServer: https://cxprivatecloud.checkmarx.net
        cxProject: App
        cxToken: ${{ secrets.CHECKMARX_TOKEN }}
        cxTeam: CxServer/SP/America/Igor-Sandbox
        cxHigh: 0
        cxMedium: 0
        cxLow: 0
        cxIncremental: true
        cxSkipIfFail: true
        cxReportPDF:  checkmarx.pdf
